name: ViaBackwards
version: 5.12.0
description: Allows the connection of older clients to newer server versions for Minecraft servers.
main: com.viaversion.viabackwards.BukkitPlugin
api-version: 1.13
folia-supported: true

authors: [Matsv, kennytv, Gerrygames, creeper123123321, ForceUpdate1, EnZaXD]
website: "https://viaversion.com/backwards"

depend: [ViaVersion]
