name: ViaBackportVisuals
version: 1.0.0
main: com.melonman106.vbfix.ViaBackportVisuals
api-version: '1.21'
depend: [ViaVersion, ViaBackwards]
commands:
  vbvisuals:
    permission: vbvisuals.admin
permissions:
  vbvisuals.admin:
    default: op
